### ISSUE TITLE
:sparkles: **Разработка технической документации** :sparkle (Парфенова))s:

### ISSUE THREAD

**Issue by DenisKozarezov** [DenisKozarezov/OkKi_Project#12]
- [ ] Написать комментарии к программному коду (функции, процедуры, классы и т.п.)
- [ ] Составить описание IDEF0- и DFD-моделям
- [x] Проконсультироваться с Программистами и Архитектором для получения наиболее полной информации
- [ ] Показать первую версию документации Мастеру и Аналитику

**Comment by DenisKozarezov** [comment]
@Parofeen Настя, я правильно тут всё указал или мне убрать что-то?

**Comment by DenisKozarezov** [comment]
> @Parofeen Настя, я правильно тут всё указал или мне убрать что-то?

Я давно составлял этот список, поэтому могу быть неточным.

**Comment by Parofeen** [comment]
Мы же определили мой фронт работ- составление руководства для пользователя.
