### ISSUE TITLE
Отчёт для технического писателя (Парфенова)

### ISSUE THREAD

**Issue by DenisKozarezov** [DenisKozarezov/OkKi_Project#2]
Как будем оформлять отчёт тех. писателю? Комментарии к коду? Включить модель в Рамусе? Не очень представляю, как это должно выглядеть 😢

**Comment by Parofeen** [comment]
Я думаю, что лучше мне лучше сконцентрироваться на составлении пользовательской документации для проекта.

**Comment by DenisKozarezov** [comment]
А как именно будет выглядеть пользовательская документация? Я правильно понял, что это будет описание, например, кнопок, слайдеров (ползунков) и прочих элементов интерфейса?)

**Comment by Parofeen** [comment]
Руководство пользователя загружено
